### ISSUE TITLE
configure config.toml to use with the systemd cgroup driver

### ISSUE THREAD

**Issue by rdxmb** [geerlingguy/ansible-role-containerd#2]
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd-systemd

**Comment by rdxmb** [comment]
checked with 

* kubeadm v1.20.6
* containerd 1.4.4-1

|                                         |                            |                                           |                                          |                           |
|-----------------------------------------|----------------------------|-------------------------------------------|------------------------------------------|---------------------------|
| containerd config                       | `SystemdCgroup = true`     | default                                   |  default                                 | `SystemdCgroup = true`    |
| kubeadm-kubelet config                  | `cgroupDriver: "cgroupfs"` | `cgroupDriver: "cgroupfs"`                | `cgroupDriver: "systemd"`                | `cgroupDriver: "systemd"` |
| kubelet status                          | kubeadm init failed 1)     | running with `cgroupDriver: cgroupfs`  2) | running with `cgroupDriver: cgroupfs` 2) | running with `cgroupDriver: systemd` 2) |

1) "The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)"
2) checked in /var/lib/kubelet/config.yaml on the nodes . Note: With kubeadm 1.21, the cgroup-driver will be set to `systemd` by default. https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/#configuring-the-kubelet-cgroup-driver.

**Comment by goshlanguage** [comment]
no-stale
